FROM node:18-alpine

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

# Compila la app para producción
RUN yarn build

# Expone el puerto que Vite usa por defecto para preview
EXPOSE 4173

# Usa el preview como servidor (modo producción)
CMD ["yarn", "preview", "--host"]
